apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange-with-arguments
spec:
  forProvider:
    vhost: demo
    exchangeSettings:
      type: fanout
      durable: true
      autoDelete: false
      arguments:
        "x-delayed-type": "direct"
        "x-expires": "300000"  # 5 minutes
  providerConfigRef:
    name: provider-rabbitmq