apiVersion: v1
kind: Secret
metadata:
  name: demo-user-credentials
  namespace: rabbitmq
stringData:
  password: "admin123"
---
apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: User
metadata:
  name: demo
spec:
  forProvider:
    username: demo
    userSettings:
      passwordSecretRef:
        namespace: rabbitmq
        name: demo-user-credentials
        key: password
      tags:
        - "administrator"
  providerConfigRef:
    name: provider-rabbitmq