apiVersion: core.rabbitmq.m.crossplane.io/v1alpha1
kind: Permissions
metadata:
  name: demo-user-permissions
  namespace: rabbitmq
spec:
  forProvider:
    vhost: demo
    user: demo
    permissions:
      configure: .*
      write: .*
      read: .*
  providerConfigRef:
    name: provider-rabbitmq
    kind: ProviderConfig
