apiVersion: core.rabbitmq.m.crossplane.io/v1alpha1
kind: Vhost
metadata:
  name: demo
  namespace: rabbitmq
spec:
  forProvider:
    hostName: demo
    vhostSettings:
      defaultQueueType: quorum
      description: "Demo Vhost"
  providerConfigRef:
    name: provider-rabbitmq
    kind: ProviderConfig