apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Binding
metadata:
  name: my-binding
spec:
  forProvider:
    vhost: demo
    source: myexchange
    destinationType: queue
    destination: test
    routingKey: "my-custom-key"
    arguments:
      test: test3
  providerConfigRef:
    name: provider-rabbitmq
