apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange
spec:
  forProvider:
    vhost: demo
    exchange_settings:
      type: fanout
      durable: true
      auto_delete: false
  providerConfigRef:
    name: provider-rabbitmq