apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange-name-in-provider
spec:
  forProvider:
    name: crossplane-exchange
    vhost: demo
    exchange_settings:
      type: direct
      durable: false
      auto_delete: true
  providerConfigRef:
    name: provider-rabbitmq