apiVersion: core.rabbitmq.m.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange-name-in-provider
  namespace: rabbitmq
spec:
  forProvider:
    name: crossplane-exchange
    vhost: demo
    exchangeSettings:
      type: direct
      durable: false
      autoDelete: true
  providerConfigRef:
    name: provider-rabbitmq
    kind: ProviderConfig