apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange
spec:
  forProvider:
    vhost: demo
    exchangeSettings:
      type: fanout
      durable: true
      autoDelete: false
  providerConfigRef:
    name: provider-rabbitmq