apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Exchange
metadata:
  name: myexchange-2
  annotations:
    crossplane.io/external-name: crossplane-exchange
spec:
  forProvider:
    vhost: demo
    exchange_settings:
      type: direct
      durable: false
      auto_delete: true
  providerConfigRef:
    name: provider-rabbitmq