apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: myqueue-name-in-provider
spec:
  forProvider:
    vhost: demo
    name: myqueue
    queueSettings:
      type: classic
      durable: true
      autoDelete: false
  providerConfigRef:
    name: provider-rabbitmq