apiVersion: core.rabbitmq.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: myqueue
spec:
  forProvider:
    vhost: demo
    queueSettings:
      arguments:
        "x-queue-type": "classic"
        "x-message-ttl": "30000"
  providerConfigRef:
    name: provider-rabbitmq