apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-rabbitmq
spec:
  tolerations:
    - effect: NoSchedule
      key: crossplane
      operator: Exists
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-rabbitmq
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/pnowy/provider-rabbitmq:v0.5.0
  controllerConfigRef:
    name: provider-rabbitmq