name: IT

on:
  pull_request: {}
  workflow_dispatch: {}

env:
  GO_VERSION: '1.23.10'
  DOCKER_BUILDX_VERSION: 'v0.23.0'
jobs:

  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "cachedir=$(make go.cachedir)" >> $GITHUB_ENV

      - name: Cache the Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.cachedir }}
          key: ${{ runner.os }}-build-integration-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-integration-tests-

      - name: Cache Go Dependencies
        uses: actions/cache@v4
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Download Go Modules
        run: make modules.download modules.check

      - name: Build Artifacts
        run: make -j2 build.all
        env:
          BUILD_ARGS: "--load"

      - name: Run Integration Tests
        run: make test-integration
